# Generated by Django 5.1.4 on 2025-01-15 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('newsletters', models.ManyToManyField(related_name='subscribers', to='newsletter.newsletter')),
            ],
        ),
    ]
