# Generated by Django 5.1.4 on 2025-01-15 11:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
