# Generated by Django 5.1.4 on 2025-01-17 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_alter_newsletter_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='short_description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
