# Generated by Django 5.1.4 on 2025-01-18 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_newsletter_short_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='short_description',
            field=models.TextField(max_length=500),
        ),
    ]
