# Generated by Django 5.1.4 on 2025-01-18 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0005_newsletter_profile_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='profile_image',
            new_name='image',
        ),
    ]
