# Generated by Django 5.1.4 on 2025-01-18 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0006_rename_profile_image_newsletter_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
